// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAix7q4IKELkoQCb0mz4XLURTvmROPwGu8',
    appId: '1:890437919694:web:8e60c98f6f535d6f25419f',
    messagingSenderId: '890437919694',
    projectId: 'shopping-app-7a01c',
    authDomain: 'shopping-app-7a01c.firebaseapp.com',
    storageBucket: 'shopping-app-7a01c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhom-TxU5CyDFmoJqFoa-5pEBMH5qHKdU',
    appId: '1:890437919694:android:c77040d7074a75ac25419f',
    messagingSenderId: '890437919694',
    projectId: 'shopping-app-7a01c',
    storageBucket: 'shopping-app-7a01c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvUI9uUEv2SSNtECbMcjy0H5vwa6JjYYg',
    appId: '1:890437919694:ios:175ee2f63f5cf8bc25419f',
    messagingSenderId: '890437919694',
    projectId: 'shopping-app-7a01c',
    storageBucket: 'shopping-app-7a01c.firebasestorage.app',
    iosBundleId: 'com.example.shopingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvUI9uUEv2SSNtECbMcjy0H5vwa6JjYYg',
    appId: '1:890437919694:ios:175ee2f63f5cf8bc25419f',
    messagingSenderId: '890437919694',
    projectId: 'shopping-app-7a01c',
    storageBucket: 'shopping-app-7a01c.firebasestorage.app',
    iosBundleId: 'com.example.shopingapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAix7q4IKELkoQCb0mz4XLURTvmROPwGu8',
    appId: '1:890437919694:web:5e8062458aa690f725419f',
    messagingSenderId: '890437919694',
    projectId: 'shopping-app-7a01c',
    authDomain: 'shopping-app-7a01c.firebaseapp.com',
    storageBucket: 'shopping-app-7a01c.firebasestorage.app',
  );
}
